collect:
  rtm:
   - Destination_gui
  apt:
   - ros-noetic-moveit
   - ros-noetic-navigation
  git:
   - url: https://github.com/seed-solutions
     repo: seed_smartactuator_sdk
   - url: https://github.com/seed-solutions
     repo: seed_r7_ros_pkg.git

run:
  rosrun:
   - seed_r7_navigation Movetest.py
  #  - rviz rviz -d `rospack find seed_r7_bringup`/rviz.rviz
  roslaunch:
   - seed_r7_bringup seed_r7_bringup.launch
   - seed_r7_navigation wheel_with_static_map.launch

